# Gradle Properties
org.gradle.jvmargs = -Xmx3G

# Compilation Options
generate_sources_jar = true
generate_javadocs_jar = false

# Testing
enable_junit_testing = true
show_testing_output = false

# Shadow
enable_shadow = false

# Set this to true if you want to use old LWJGL2 methods.
enable_lwjglx = true

# Mod Information
# HIGHLY RECOMMEND complying with SemVer for mod_version: https://semver.org/
mod_version = 2.4
root_package = com.zzhalex233
mod_id = ae2cellrender
mod_name = AE2 Cell Render

# Mod Metadata (Optional)
mod_description = Client-side AE2 drive cell color rendering for 1.12.2 AE2UEL.
mod_url = https://github.com/zzhalex233/AE2-Cell-Render
mod_update_json =
# Delimit authors with commas
mod_authors = zzhalex233
mod_credits =
mod_logo_path =

# Run Configurations
# If multiple arguments/tweak classes are stated, use spaces as the delimiter
minecraft_username = Developer
extra_jvm_args =
enable_foundation_debug = false

# Maven Publishing (Provide secret: MAVEN_USER, MAVEN_PASS)
publish_to_maven = false
# Good for debugging artifacts before uploading to remote maven
# GitHub actions won't run if this is true, test this by running the task `publishToMavenLocal`
publish_to_local_maven = false
maven_name = ${mod_name}
maven_url =

# If any properties changes below this line, refresh gradle again to ensure everything is working correctly.
# ----------------------------------------------------------------------------------------------------------------------

# Access Transformers
use_access_transformer = true

# Coremods
is_coremod = true
coremod_includes_mod = true
coremod_plugin_class_name = com.zzhalex233.ae2cellrender.mixin.AE2CellRenderMixinsCore

# Mixins
mixin_configs = mixins.ae2cellrender.json
mixin_booter_version = 10.7

# AssetMover
use_asset_mover = false
asset_mover_version = 2.5
